### ISSUE TITLE
Application crashes when opening a conversation that includes an XMPP URI, e.g. xmpp:someone@example.com

### ISSUE THREAD

**Issue by pixel1138** [kriztan/Pix-Art-Messenger#273]
#### General information

* **Version:  2.1.3**
* **Device:  Samsung Galaxy S8+**
* **Android Version:  8.0**
* **Samsung Experience version: 9.0**

#### Steps to reproduce

1. Receive a message that includes an XMPP URI, e.g. xmpp:someone@example.com
2. Navigate to the message either by tapping the notification or tapping the conversation in the list
3. App will crash

#### Expected result

See the conversation

#### Actual result

App crashes

#### Debug output

Version: 2.1.3
Last Update: 2018-11-12
SHA-1: 6f:cc:84:1e:19:a0:b4:83:ae:4e:8e:6b:57:e1:5a:31:14:fe:71:c1

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at de.pixart.messenger.ui.adapter.MessageAdapter.displayXmppMessage(MessageAdapter.java:416)
	at de.pixart.messenger.ui.adapter.MessageAdapter.getView(MessageAdapter.java:946)
	at android.widget.AbsListView.obtainView(AbsListView.java:3189)
	at android.widget.ListView.makeAndAddView(ListView.java:2197)
	at android.widget.ListView.fillSpecific(ListView.java:1522)
	at android.widget.ListView.layoutChildren(ListView.java:1929)
	at android.widget.AbsListView.onLayout(AbsListView.java:2961)
	at android.view.View.layout(View.java:20836)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:20836)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20836)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20836)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20836)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20836)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20836)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20836)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:944)
	at android.view.View.layout(View.java:20836)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2948)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2635)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1779)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7810)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

````
adb -d logcat -v time | FINDSTR Pix-Art > logcat.txt
````

**Comment by kriztan** [comment]
Thanks, I'll check this

**Comment by ramsonline** [comment]
I have the same Problem...

**Comment by kriztan** [comment]
should be fixed with d1098d8bfb635b231085d019cfd2349be264bbf9
