### ISSUE TITLE
Web preview crash

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#305]
#### General information

* **Version:** b6c12fe50adf411b30ee5bdcba9cea4916fc467d
* **Android Version:** AOSP Pie Jan 2019

#### Steps to reproduce

1. share a link ( I tested with one from mobile.twitter.com)

#### Expected result

Preview

#### Actual result

A site favicon and then crash on chat open

I can't repro at will, it just happened. One way to get rid of it was to write enough messages in that chat so the preview bubble was not on screen any more, and then clean history.

#### Debug output

```
E AndroidRuntime: Process: de.pixart.messenger, PID: 25365
E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.URI.getHost()' on a null object reference
E AndroidRuntime: 	at io.github.ponnamkarthik.richlinkpreview.RichPreview$getData.doInBackground(RichPreview.java:143)
E AndroidRuntime: 	at io.github.ponnamkarthik.richlinkpreview.RichPreview$getData.doInBackground(RichPreview.java:35)
E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E AndroidRuntime: 	... 4 more
```

**Comment by kriztan** [comment]
should be fixed in c820c915a20a5e90fd3d98b4f18b182f6a97235a
Feel free to reopen it if it's not fixed
