### ISSUE TITLE
Issues accessing storage

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#410]
2.3.0 Github
Xiaomi MIUI11 Android 10

Allow storage permission, try to attach a file/picture, choose from recents/gallery/storage/etc, see preview of that image in input area, see toast saying `general I/O, Maybe you've don't have free space?`, long press failed bubble says `/storage/emulated/0/path/file.jpg open failed: EACCES (Permission denied)`

No issues with Conversations

Will try to get some logcats later.

**Comment by kriztan** [comment]
Thanks, I've checked the permissions. They are correct. I'll look for a soloution. Adb logs would be good.

**Comment by licaon-kter** [comment]
And the log, attach file, menu, device storage, folder, file:
```
W System.err: java.io.FileNotFoundException: /storage/emulated/0/Transfer/1920x1200.jpg: open failed: EACCES (Permission denied)
W System.err:    at libcore.io.IoBridge.open(IoBridge.java:496)
W System.err:    at java.io.FileInputStream.<init>(FileInputStream.java:159)
W System.err:    at de.pixart.messenger.http.HttpUploadConnection.upload(HttpUploadConnection.java:162)
W System.err:    at de.pixart.messenger.http.HttpUploadConnection.access$500(HttpUploadConnection.java:30)
W System.err:    at de.pixart.messenger.http.HttpUploadConnection$1.lambda$success$0$HttpUploadConnection$1(HttpUploadConnection.java:142)
W System.err:    at de.pixart.messenger.http.-$$Lambda$HttpUploadConnection$1$UIzX1ofCQglX791SRuyImFMqjTE.run(Unknown Source:4)
W System.err:    at de.pixart.messenger.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W System.err:    at java.lang.Thread.run(Thread.java:919)
W System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W System.err:    at libcore.io.Linux.open(Native Method)
W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W System.err:    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W System.err:    at android.app.ActivityThread$AndroidOs.open(Unknown Source:15)
W System.err:    at libcore.io.IoBridge.open(IoBridge.java:482)
W System.err:    ... 9 more
```

**Comment by kriztan** [comment]
...and maybe ad32a6889b6fd23969eed5e03d9dbe1b02063b1e

**Comment by licaon-kter** [comment]
Fixed, thanks
