### ISSUE TITLE
Connecting to a server with a self signed cert? 

### ISSUE THREAD

**Issue by raw-raw** [kriztan/Pix-Art-Messenger#491]
Hello. 
Whilst I have no problems to connect from Windows and Linux to my own xmpp server which has a self signed certificate, I cannot get Pixart to connect. I tried the setting which distrusts all CAs but I dont even get asked to review the certificate.
Pixart just keeps saying "connecting" but nothing happens. I'd at least expect an error message of some kind. I first thought I messed up the DNS settings or they didn't propagate quick enough.. But i'm pretty confident this has to do with the xmpp server's certificate. 

Is there anything I can do? I dont want to use aTalk because it hurts my eyes.

**Comment by kriztan** [comment]
Please generate adb logs.

**Comment by raw-raw** [comment]
Digging deeper it turned out **not** to be a certificate issue but a resolver issue. Tried clearing the cache but it didn't help. Please note that aTalk on the same device can in fact connect.
First
>05-25 01:23:45.188  5633  5633 I Pix-Art_Messenger: AxolotlService (pixart@mydomain.example): Could not retrieve axolotl registration id for account pixart@mydomain.example
05-25 01:23:45.188  5633  5633 I Pix-Art_Messenger: AxolotlService : Generating axolotl registration ID...
05-25 01:23:45.189  5633  5633 W Pix-Art_Messenger: AxolotlService (pixart@mydomain.example): Could not retrieve current prekey id for account pixart@mydomain.example
05-25 01:23:45.196  5633 14046 D Pix-Art_Messenger: pixart@mydomain.example: connecting
05-25 01:23:45.198  5633  5633 D Pix-Art_Messenger: ForegroundService: on

Then

> 05-25 01:23:45.387  5633 14056 W System.err: java.net.UnknownHostException: Unable to resolve host "xmpp.mydomain.example": No address associated with hostname
05-25 01:23:45.388  5633 14056 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
05-25 01:23:45.388  5633 14056 W System.err: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
05-25 01:23:45.388  5633 14056 W System.err: 	at java.net.InetAddress.getByName(InetAddress.java:1108)
05-25 01:23:45.388  5633 14056 W System.err: 	at eu.siacs.conversations.utils.Resolver$Result.fromRecord(Resolver.java:403)
05-25 01:23:45.388  5633 14056 W System.err: 	at eu.siacs.conversations.utils.Resolver.lambda$resolveSrv$4(Resolver.java:206)
05-25 01:23:45.388  5633 14056 W System.err: 	at eu.siacs.conversations.utils.-$$Lambda$Resolver$Lkn-yOxUpgn5F3VfoB4s7FmzVhs.run(Unknown Source:8)
05-25 01:23:45.388  5633 14056 W System.err: 	at java.lang.Thread.run(Thread.java:764)
05-25 01:23:45.388  5633 14056 W System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
05-25 01:23:45.388  5633 14056 W System.err: 	at libcore.io.Linux.android_getaddrinfo(Native Method)
05-25 01:23:45.388  5633 14056 W System.err: 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
05-25 01:23:45.388  5633 14056 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
05-25 01:23:45.388  5633 14056 W System.err: 	... 6 more
05-25 01:23:45.396  5633 14058 W System.err: java.net.UnknownHostException: Unable to resolve host "xmpp.mydomain.example": No address associated with hostname
05-25 01:23:45.396  5633 14058 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:126)
05-25 01:23:45.396  5633 14058 W System.err: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
05-25 01:23:45.396  5633 14058 W System.err: 	at java.net.InetAddress.getByName(InetAddress.java:1108)
05-25 01:23:45.396  5633 14058 W System.err: 	at eu.siacs.conversations.utils.Resolver$Result.fromRecord(Resolver.java:403)
05-25 01:23:45.396  5633 14058 W System.err: 	at eu.siacs.conversations.utils.Resolver.lambda$resolveSrv$4(Resolver.java:206)
05-25 01:23:45.396  5633 14058 W System.err: 	at eu.siacs.conversations.utils.-$$Lambda$Resolver$Lkn-yOxUpgn5F3VfoB4s7FmzVhs.run(Unknown Source:8)
05-25 01:23:45.396  5633 14058 W System.err: 	at java.lang.Thread.run(Thread.java:764)
05-25 01:23:45.397  5633 14046 D Pix-Art_Messenger: Resolver: happy eyeball (3fecb67ab2ceccf9) with [Result{ip='null', hostname='xmpp.mydomain.example', port=5223, directTls=true, authenticated=false, priority=5}, Result{ip='null', hostname='xmpp.mydomain.example', port=5222, directTls=false, authenticated=false, priority=5}]
05-25 01:23:45.398  5633 14061 D Pix-Art_Messenger: Resolver did not get IP:port (null:5223)
05-25 01:23:45.398  5633 14062 D Pix-Art_Messenger: Resolver did not get IP:port (null:5222)
05-25 01:23:45.399  5633 14046 I Pix-Art_Messenger: Resolver: happy eyeball (3fecb67ab2ceccf9) unable to connect to one address
05-25 01:23:45.399  5633 14046 E Pix-Art_Messenger: pixart@mydomain.example: Resolver results were empty

For privacy purposes i replaced my domain.

**Comment by kriztan** [comment]
@genofire can you say anything about this?

**Comment by genofire** [comment]
@raw-raw it looks like ... he was not able to fetch the IP-Addresses from DNS and so was not able to connect.
```
05-25 01:23:45.396 5633 14058 W System.err: java.net.UnknownHostException: Unable to resolve host "xmpp.mydomain.example": No address associated with hostname
```
appears multiple time.

Is now everthing fine?

**Comment by raw-raw** [comment]
I'm out of ideas. I reinstalled the app but the issue persists.
In fact the issue seems to exist with all forks of conversations that I've tried.. But only on this device.

**Comment by kriztan** [comment]
Maybe this could be a ROM failure.

**Comment by raw-raw** [comment]
> Maybe this could be a ROM failure.

Since the OS is stock but Miui (Redmi Note 8 Pro) I think this is very plausible. All I can do is wait and hope that the internal dns cache expires after some period of time or I will need to factory reset. 

Sorry for bugging you and thank you for trying to help he!

**Comment by underhandedness** [comment]
try

enable Private DNS.  Setup free NextDNS.io account to view your logs

_Now mobile adblocking is within reach of everyone_
