### ISSUE TITLE
Location permission problem

### ISSUE THREAD

**Issue by kriztan** [kriztan/Pix-Art-Messenger#90]
#### General information

* **Version:** 1.13.2
* **Device:** SGS 3
* **Android Version:** Android 6.0 crDroid

#### Steps to reproduce

1. start location service
2. app crashes

#### Expected result

...location should be displayed

#### Debug output

````
Version: 1.13.2
Last Update: 2016-06-06
SHA-1: fa:b7:c7:cf:9f:35:54:9b:3f:22:d5:f3:9a:fd:de:71:d0:2c:90:c0

java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION
    at maps.ag.t.c(Unknown Source)
    at uz.onTransact(:com.google.android.gms.DynamiteModulesB:274)
    at android.os.Binder.transact(Binder.java:387)
    at com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.setMyLocationEnabled(Unknown Source)
    at com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(Unknown Source)
    at eu.siacs.conversations.ui.ShowLocationActivity.onMapReady(ShowLocationActivity.java:107)
    at com.google.android.gms.maps.MapFragment$zza$1.zza(Unknown Source)
    at com.google.android.gms.maps.internal.zzo$zza.onTransact(Unknown Source)
    at android.os.Binder.transact(Binder.java:387)
    at wv.a(:com.google.android.gms.DynamiteModulesB:82)
    at maps.ag.t$5.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
````

**Comment by kriztan** [comment]
Fixed via aca07ad7418ed366acb144788844a63d9d154f41
